//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameOfWar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public System.Guid CardID { get; set; }
        public string Suit { get; set; }
        public int Value { get; set; }
        public string Face { get; set; }
    }
}
